name: Website
highlighter: rouge
baseurl: "/website-1"
exclude:
  - .bundle
  - .git
  - .gitignore
  - bin
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
markdown: kramdown
future: true
collections:
- events
